name: Labeler ROS1
on:
  pull_request:
    branches:
      - master

jobs:
  triage-ros1:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/labeler@v2
        with:
          repo-token: "${{ secrets.GITHUB_TOKEN }}"
